const pool = require('./config/db');

const clients = [
  {
    id: 'VM00000001',
    name: 'Vikramaditya Singhania',
    email: 'vikram.singhania@example.com',
    phone: '9819001101',
    alternate_phone: '9819001102',
    address: 'Penthouse 18A, Sea Face Towers, Worli',
    city: 'Mumbai',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 150,
    assigned_sales_id: 'VMU0002',
    profile_image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    preferred_category: 'Cook',
    locality: 'Worli Sea Face',
    house_type: '4BHK Penthouse',
    family_size: 4,
    has_pets: 1,
    pet_details: '1 Golden Retriever (friendly)',
    has_elderly_members: 1,
    has_children: 1,
    children_count: 2,
    required_skills: 'North Indian, Continental, Diet Cooking',
    budget_range: '₹25,000 - ₹35,000',
    source: 'Website Inquiry',
    remarks: 'VIP Client. Looking for an experienced chef who can prepare hygienic North Indian & Continental meals.',
    service_type: '24 Hours Live-in',
    work_timings: '24 Hours',
    food_preference: 'Vegetarian + Egg',
    gender_preference: 'Female',
    preferred_languages: 'Hindi, English',
    religion_preference: 'Any / No Preference',
    expected_joining: 'Immediate (Within 1-2 Days)'
  },
  {
    id: 'VM00000002',
    name: 'Priya & Rajesh Oberoi',
    email: 'priya.oberoi@example.com',
    phone: '9819001103',
    alternate_phone: '9819001104',
    address: 'Flat 1204, Oberoi Exquisite, Goregaon East',
    city: 'Mumbai',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 50,
    assigned_sales_id: 'VMU0002',
    profile_image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    preferred_category: 'Nanny',
    locality: 'Goregaon East',
    house_type: '3BHK Apartment',
    family_size: 3,
    has_pets: 0,
    pet_details: null,
    has_elderly_members: 0,
    has_children: 1,
    children_count: 1,
    required_skills: 'Toddler care, Infant hygiene, Storytelling, Meal prep',
    budget_range: '₹20,000 - ₹28,000',
    source: 'Instagram / Facebook',
    remarks: 'Both parents working in tech. Need dedicated nanny for 1.5 year old baby.',
    service_type: '12 Hours Day Duty',
    work_timings: '8:00 AM - 8:00 PM',
    food_preference: 'Any / No Preference',
    gender_preference: 'Female',
    preferred_languages: 'Hindi, English',
    religion_preference: 'Any / No Preference',
    expected_joining: 'Within 1 Week'
  },
  {
    id: 'VM00000003',
    name: 'Dr. Arvind Kulkarni',
    email: 'dr.kulkarni@example.com',
    phone: '9819001105',
    alternate_phone: '9819001106',
    address: 'Bungalow 7, Prabhat Road, Lane 4, Deccan',
    city: 'Pune',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 0,
    assigned_sales_id: 'VMU0001',
    profile_image_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
    preferred_category: 'Elderly Care',
    locality: 'Prabhat Road',
    house_type: 'Independent Villa / Bungalow',
    family_size: 2,
    has_pets: 0,
    pet_details: null,
    has_elderly_members: 1,
    has_children: 0,
    children_count: null,
    required_skills: 'Medicine assistance, Blood pressure monitoring, Mobility support',
    budget_range: '₹22,000 - ₹30,000',
    source: 'Referral',
    remarks: 'Care for 78-year-old mother. Needs compassionate caretaker.',
    service_type: '24 Hours Live-in',
    work_timings: '24 Hours',
    food_preference: 'Pure Vegetarian',
    gender_preference: 'Female',
    preferred_languages: 'Marathi, Hindi',
    religion_preference: 'Hindu',
    expected_joining: 'Immediate (Within 1-2 Days)'
  },
  {
    id: 'VM00000004',
    name: 'Sameer & Ananya Mehta',
    email: 'sameer.mehta@example.com',
    phone: '9819001107',
    alternate_phone: '9819001108',
    address: 'Tower 2, Flat 901, Hiranandani Gardens, Powai',
    city: 'Mumbai',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 200,
    assigned_sales_id: 'VMU0002',
    profile_image_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
    preferred_category: 'House Maid',
    locality: 'Powai',
    house_type: '3BHK Apartment',
    family_size: 4,
    has_pets: 1,
    pet_details: '1 Persian Cat',
    has_elderly_members: 0,
    has_children: 1,
    children_count: 1,
    required_skills: 'Deep cleaning, Dusting, Laundry, Dishwashing',
    budget_range: '₹16,000 - ₹22,000',
    source: 'Google Search',
    remarks: 'Active contract. Candidate matched successfully.',
    service_type: '24 Hours Live-in',
    work_timings: '24 Hours',
    food_preference: 'Jain / Vegetarian',
    gender_preference: 'Female',
    preferred_languages: 'Hindi, Gujarati',
    religion_preference: 'Any / No Preference',
    expected_joining: 'Immediate (Within 1-2 Days)'
  },
  {
    id: 'VM00000005',
    name: 'Rohan Kapoor',
    email: 'rohan.kapoor@example.com',
    phone: '9819001109',
    alternate_phone: '9819001110',
    address: 'Flat 602, Silver Beach Apartments, Juhu',
    city: 'Mumbai',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 0,
    assigned_sales_id: 'VMU0002',
    profile_image_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400',
    preferred_category: 'House Maid',
    locality: 'Juhu',
    house_type: '4BHK Apartment',
    family_size: 5,
    has_pets: 1,
    pet_details: '2 Labrador dogs',
    has_elderly_members: 1,
    has_children: 1,
    children_count: 2,
    required_skills: 'Cooking, Cleaning, Pet handling',
    budget_range: '₹22,000 - ₹30,000',
    source: 'Direct / Walk-in',
    remarks: 'Spoke with client on phone. Requested 3 candidate profiles.',
    service_type: '24 Hours Live-in',
    work_timings: '24 Hours',
    food_preference: 'Non-Vegetarian',
    gender_preference: 'Female',
    preferred_languages: 'Hindi, English',
    religion_preference: 'Any / No Preference',
    expected_joining: 'Within 1-2 Weeks'
  },
  {
    id: 'VM00000006',
    name: 'Nisha Deshmukh',
    email: 'nisha.deshmukh@example.com',
    phone: '9819001111',
    alternate_phone: '9819001112',
    address: 'Row House 14, Koregaon Park Plaza',
    city: 'Pune',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 25,
    assigned_sales_id: 'VMU0002',
    profile_image_url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400',
    preferred_category: 'Cook',
    locality: 'Koregaon Park',
    house_type: 'Row House / Villa',
    family_size: 3,
    has_pets: 0,
    pet_details: null,
    has_elderly_members: 0,
    has_children: 1,
    children_count: 1,
    required_skills: 'Maharashtrian cuisine, South Indian breakfast, Healthy meal prep',
    budget_range: '₹18,000 - ₹25,000',
    source: 'Website Inquiry',
    remarks: 'Interested in Sarita Bhosle (CN00000009). Video interview scheduled.',
    service_type: '12 Hours Day Duty',
    work_timings: '7:30 AM - 7:30 PM',
    food_preference: 'Vegetarian',
    gender_preference: 'Female',
    preferred_languages: 'Marathi, Hindi',
    religion_preference: 'Hindu',
    expected_joining: 'Immediate (Within 1-2 Days)'
  },
  {
    id: 'VM00000007',
    name: 'Kabir & Tara Roy',
    email: 'kabir.roy@example.com',
    phone: '9819001113',
    alternate_phone: '9819001114',
    address: 'Flat 1502, Lodha Bellissimo, Mahalaxmi',
    city: 'Mumbai',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 0,
    assigned_sales_id: 'VMU0001',
    profile_image_url: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400',
    preferred_category: 'Nanny',
    locality: 'Mahalaxmi',
    house_type: '3BHK Apartment',
    family_size: 3,
    has_pets: 0,
    pet_details: null,
    has_elderly_members: 0,
    has_children: 1,
    children_count: 1,
    required_skills: 'Newborn care, Sterilization, Sleep routine management',
    budget_range: '₹22,000 - ₹32,000',
    source: 'Referral',
    remarks: 'First-time parents. Seeking trusted nanny with hospital or verified daycare experience.',
    service_type: '24 Hours Live-in',
    work_timings: '24 Hours',
    food_preference: 'Any / No Preference',
    gender_preference: 'Female',
    preferred_languages: 'Hindi, English, Bengali',
    religion_preference: 'Any / No Preference',
    expected_joining: 'Immediate (Within 1-2 Days)'
  },
  {
    id: 'VM00000008',
    name: 'Ashok Chawla',
    email: 'ashok.chawla@example.com',
    phone: '9819001115',
    alternate_phone: '9819001116',
    address: 'Villa 9, Aamby Valley Road, Lonavala',
    city: 'Pune',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 0,
    assigned_sales_id: 'VMU0002',
    profile_image_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400',
    preferred_category: 'Driver',
    locality: 'Bavdhan',
    house_type: 'Independent Villa / Bungalow',
    family_size: 4,
    has_pets: 1,
    pet_details: '1 Beagle',
    has_elderly_members: 1,
    has_children: 0,
    children_count: null,
    required_skills: 'Automatic/Manual luxury cars, Highway driving, Pune-Mumbai route expertise',
    budget_range: '₹22,000 - ₹28,000',
    source: 'Google Ads',
    remarks: 'Requires chauffeur for daily business commute and weekend travel.',
    service_type: '12 Hours Day Duty',
    work_timings: '8:30 AM - 8:30 PM',
    food_preference: 'Any / No Preference',
    gender_preference: 'Male',
    preferred_languages: 'Hindi, Marathi, English',
    religion_preference: 'Any / No Preference',
    expected_joining: 'Within 1-2 Days'
  },
  {
    id: 'VM00000009',
    name: 'Siddharth & Natasha Bajaj',
    email: 'siddharth.bajaj@example.com',
    phone: '9819001117',
    alternate_phone: '9819001118',
    address: 'Tower A, 21st Floor, World One, Lower Parel',
    city: 'Mumbai',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 250,
    assigned_sales_id: 'VMU0002',
    profile_image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
    preferred_category: 'House Maid',
    locality: 'Lower Parel',
    house_type: '4BHK Apartment',
    family_size: 4,
    has_pets: 0,
    pet_details: null,
    has_elderly_members: 1,
    has_children: 1,
    children_count: 1,
    required_skills: 'Wardrobe management, Deep cleaning, Premium appliances handling',
    budget_range: '₹20,000 - ₹26,000',
    source: 'Direct / Walk-in',
    remarks: 'Active contract. Satisfied with service.',
    service_type: '24 Hours Live-in',
    work_timings: '24 Hours',
    food_preference: 'Vegetarian',
    gender_preference: 'Female',
    preferred_languages: 'Hindi, English',
    religion_preference: 'Any / No Preference',
    expected_joining: 'Immediate (Within 1-2 Days)'
  },
  {
    id: 'VM00000010',
    name: 'Deepa Bhattacharya',
    email: 'deepa.b@example.com',
    phone: '9819001119',
    alternate_phone: '9819001120',
    address: 'A-502, Kalpataru Riverside, Panvel',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    status: 'followUp',
    loyalty_points: 30,
    assigned_sales_id: 'VMU0001',
    profile_image_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400',
    preferred_category: 'Patient Care',
    locality: 'Panvel',
    house_type: '2BHK Apartment',
    family_size: 2,
    has_pets: 0,
    pet_details: null,
    has_elderly_members: 1,
    has_children: 0,
    children_count: null,
    required_skills: 'Post-surgery recovery assistance, Medication schedule, Patient mobility',
    budget_range: '₹20,000 - ₹28,000',
    source: 'Hospital Referral',
    remarks: 'Need verified patient care attendant for elderly father recovering from knee replacement.',
    service_type: '24 Hours Live-in',
    work_timings: '24 Hours',
    food_preference: 'Bengali / Vegetarian / Fish',
    gender_preference: 'Female',
    preferred_languages: 'Bengali, Hindi',
    religion_preference: 'Any / No Preference',
    expected_joining: 'Immediate (Within 1-2 Days)'
  }
];

const candidates = [
  {
    id: 'CN00000001',
    full_name: 'Sunita Devi',
    phone: '9820112201',
    alternate_phone: '9820112202',
    age: 28,
    address: 'Room 14, Sai Krupa Chawl, Santacruz East',
    city: 'Mumbai',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: '10th Pass',
    experience_years: 4,
    languages: 'Hindi, Marathi',
    category: 'House Maid',
    expected_salary: '₹14,000 - ₹18,000',
    status: 'readyToPlace',
    is_police_verified: 1,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Sunita+Devi',
    pan_doc_url: 'https://dummyimage.com/600x400/004d40/fff.png&text=PAN+Sunita+Devi',
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Clearance+Sunita+Devi',
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Report+Fit',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
    source: 'Field Sourcing'
  },
  {
    id: 'CN00000002',
    full_name: 'Rekha Sharma',
    phone: '9820112203',
    alternate_phone: '9820112204',
    age: 34,
    address: 'Flat 102, Shanti Nagar, Ghatkopar West',
    city: 'Mumbai',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: '12th Pass',
    experience_years: 6,
    languages: 'Hindi, English, Gujarati',
    category: 'Cook',
    expected_salary: '₹20,000 - ₹25,000',
    status: 'readyToPlace',
    is_police_verified: 1,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Rekha+Sharma',
    pan_doc_url: 'https://dummyimage.com/600x400/004d40/fff.png&text=PAN+Rekha+Sharma',
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Clearance+Rekha',
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Cleared',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
    source: 'Referral'
  },
  {
    id: 'CN00000003',
    full_name: 'Pooja Jadhav',
    phone: '9820112205',
    alternate_phone: '9820112206',
    age: 26,
    address: 'Plot 45, Sector 19, Vashi',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: 'Graduate',
    experience_years: 3,
    languages: 'Marathi, Hindi, English',
    category: 'Nanny',
    expected_salary: '₹18,000 - ₹22,000',
    status: 'verificationPending',
    is_police_verified: 0,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Pooja+Jadhav',
    pan_doc_url: null,
    passport_doc_url: null,
    police_verification_doc_url: null,
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Passed',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    source: 'Direct / Walk-in'
  },
  {
    id: 'CN00000004',
    full_name: 'Anita Yadav',
    phone: '9820112207',
    alternate_phone: '9820112208',
    age: 32,
    address: 'Gali 3, Janata Colony, Jogeshwari East',
    city: 'Mumbai',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: '8th Pass',
    experience_years: 5,
    languages: 'Hindi',
    category: 'Elderly Care',
    expected_salary: '₹16,000 - ₹20,000',
    status: 'readyToPlace',
    is_police_verified: 1,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Anita+Yadav',
    pan_doc_url: 'https://dummyimage.com/600x400/004d40/fff.png&text=PAN+Anita+Yadav',
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Verified',
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Cleared',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400',
    source: 'Agency Partner'
  },
  {
    id: 'CN00000005',
    full_name: 'Lakshmi Patil',
    phone: '9820112209',
    alternate_phone: '9820112210',
    age: 30,
    address: 'B-12, Lokmanya Nagar, Thane West',
    city: 'Thane',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: '10th Pass',
    experience_years: 4,
    languages: 'Marathi, Hindi',
    category: 'House Maid',
    expected_salary: '₹18,000 - ₹22,000',
    status: 'readyToPlace',
    is_police_verified: 1,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Lakshmi+Patil',
    pan_doc_url: null,
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Clearance+Lakshmi',
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Fit',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400',
    source: 'Field Sourcing'
  },
  {
    id: 'CN00000006',
    full_name: 'Ramesh Shinde',
    phone: '9820112211',
    alternate_phone: '9820112212',
    age: 38,
    address: 'Building 4, MHADA Colony, Goregaon East',
    city: 'Mumbai',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: '10th Pass',
    experience_years: 8,
    languages: 'Hindi, Marathi',
    category: 'Driver',
    expected_salary: '₹22,000 - ₹26,000',
    status: 'readyToPlace',
    is_police_verified: 1,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Ramesh+Shinde',
    pan_doc_url: 'https://dummyimage.com/600x400/004d40/fff.png&text=PAN+Ramesh+Shinde',
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Clearance+Ramesh',
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Cleared',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    source: 'Direct / Walk-in'
  },
  {
    id: 'CN00000007',
    full_name: 'Geeta Kamble',
    phone: '9820112213',
    alternate_phone: '9820112214',
    age: 29,
    address: 'Chawl No. 8, Kurla West',
    city: 'Mumbai',
    state: 'Maharashtra',
    religion: 'Buddhist',
    education: '10th Pass',
    experience_years: 3,
    languages: 'Marathi, Hindi',
    category: 'House Maid',
    expected_salary: '₹14,000 - ₹16,000',
    status: 'medicalPending',
    is_police_verified: 1,
    is_medical_cleared: 0,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Geeta+Kamble',
    pan_doc_url: null,
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Verified+Geeta',
    medical_clearance_doc_url: null,
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400',
    source: 'Social Media Ad'
  },
  {
    id: 'CN00000008',
    full_name: 'Kavita Pawar',
    phone: '9820112215',
    alternate_phone: '9820112216',
    age: 31,
    address: 'Near Ganpati Temple, Kothrud',
    city: 'Pune',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: '12th Pass',
    experience_years: 5,
    languages: 'Marathi, Hindi, English',
    category: 'Patient Care',
    expected_salary: '₹20,000 - ₹24,000',
    status: 'readyToPlace',
    is_police_verified: 1,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Kavita+Pawar',
    pan_doc_url: 'https://dummyimage.com/600x400/004d40/fff.png&text=PAN+Kavita+Pawar',
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Clearance+Kavita',
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Clearance+Passed',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400',
    source: 'Referral'
  },
  {
    id: 'CN00000009',
    full_name: 'Sarita Bhosle',
    phone: '9820112217',
    alternate_phone: '9820112218',
    age: 35,
    address: 'Flat 301, Ganga Heights, Hadapsar',
    city: 'Pune',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: '10th Pass',
    experience_years: 7,
    languages: 'Marathi, Hindi',
    category: 'Cook',
    expected_salary: '₹22,000 - ₹25,000',
    status: 'readyToPlace',
    is_police_verified: 1,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Sarita+Bhosle',
    pan_doc_url: 'https://dummyimage.com/600x400/004d40/fff.png&text=PAN+Sarita+Bhosle',
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Clearance+Sarita',
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Passed',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    source: 'Field Sourcing'
  },
  {
    id: 'CN00000010',
    full_name: 'Meena Gupta',
    phone: '9820112219',
    alternate_phone: '9820112220',
    age: 27,
    address: 'Plot 12, Shivaji Nagar, Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
    religion: 'Hindu',
    education: '12th Pass',
    experience_years: 3,
    languages: 'Hindi, English',
    category: 'Nanny',
    expected_salary: '₹18,000 - ₹20,000',
    status: 'readyToPlace',
    is_police_verified: 1,
    is_medical_cleared: 1,
    aadhaar_doc_url: 'https://dummyimage.com/600x400/003366/fff.png&text=Aadhaar+Meena+Gupta',
    pan_doc_url: 'https://dummyimage.com/600x400/004d40/fff.png&text=PAN+Meena+Gupta',
    passport_doc_url: null,
    police_verification_doc_url: 'https://dummyimage.com/600x400/b71c1c/fff.png&text=Police+Clearance+Meena',
    medical_clearance_doc_url: 'https://dummyimage.com/600x400/1b5e20/fff.png&text=Medical+Cleared',
    sourced_by_id: 'VMU0003',
    profile_image_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400',
    source: 'Field Sourcing'
  }
];

async function ensureTableColumns() {
  const clientCols = [
    { name: 'service_type', type: "VARCHAR(100) DEFAULT '24 Hours Live-in'" },
    { name: 'work_timings', type: "VARCHAR(100) DEFAULT '24 Hours'" },
    { name: 'food_preference', type: "VARCHAR(100) DEFAULT 'Any / No Preference'" },
    { name: 'gender_preference', type: "VARCHAR(50) DEFAULT 'Female'" },
    { name: 'preferred_languages', type: "VARCHAR(255) DEFAULT 'Hindi'" },
    { name: 'religion_preference', type: "VARCHAR(100) DEFAULT 'Any / No Preference'" },
    { name: 'expected_joining', type: "VARCHAR(100) DEFAULT 'Immediate (Within 1-2 Days)'" },
    { name: 'contract_duration', type: "VARCHAR(100) DEFAULT '1 Year'" }
  ];

  for (const col of clientCols) {
    try {
      await pool.execute(`ALTER TABLE clients ADD COLUMN ${col.name} ${col.type}`);
    } catch (e) {
      // Ignored if column already exists
    }
  }

  const candidateCols = [
    { name: 'source', type: "VARCHAR(100) DEFAULT 'Direct / Walk-in'" }
  ];

  for (const col of candidateCols) {
    try {
      await pool.execute(`ALTER TABLE candidates ADD COLUMN ${col.name} ${col.type}`);
    } catch (e) {
      // Ignored if column already exists
    }
  }
}

(async () => {
  try {
    console.log('Ensuring schema columns are up to date...');
    await ensureTableColumns();

    // Clean up temporary seed IDs
    await pool.execute(`DELETE FROM clients WHERE id LIKE 'CLI-SEED-%'`);
    await pool.execute(`DELETE FROM candidates WHERE id LIKE 'CAN-SEED-%'`);

    console.log('Seeding 10 full-data Clients...');
    for (const c of clients) {
      await pool.execute(
        `INSERT INTO clients 
        (id, name, email, phone, alternate_phone, address, city, state, status, loyalty_points, assigned_sales_id, profile_image_url, preferred_category, locality, house_type, family_size, has_pets, pet_details, has_elderly_members, has_children, children_count, required_skills, budget_range, source, remarks, service_type, work_timings, food_preference, gender_preference, preferred_languages, religion_preference, expected_joining) 
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE 
          name=VALUES(name), email=VALUES(email), phone=VALUES(phone), alternate_phone=VALUES(alternate_phone),
          address=VALUES(address), city=VALUES(city), state=VALUES(state), status=VALUES(status),
          loyalty_points=VALUES(loyalty_points), assigned_sales_id=VALUES(assigned_sales_id),
          profile_image_url=VALUES(profile_image_url), preferred_category=VALUES(preferred_category),
          locality=VALUES(locality), house_type=VALUES(house_type), family_size=VALUES(family_size),
          has_pets=VALUES(has_pets), pet_details=VALUES(pet_details), has_elderly_members=VALUES(has_elderly_members),
          has_children=VALUES(has_children), children_count=VALUES(children_count), required_skills=VALUES(required_skills),
          budget_range=VALUES(budget_range), source=VALUES(source), remarks=VALUES(remarks),
          service_type=VALUES(service_type), work_timings=VALUES(work_timings), food_preference=VALUES(food_preference),
          gender_preference=VALUES(gender_preference), preferred_languages=VALUES(preferred_languages),
          religion_preference=VALUES(religion_preference), expected_joining=VALUES(expected_joining)`,
        [
          c.id, c.name, c.email, c.phone, c.alternate_phone, c.address, c.city, c.state, c.status,
          c.loyalty_points, c.assigned_sales_id, c.profile_image_url, c.preferred_category,
          c.locality, c.house_type, c.family_size, c.has_pets, c.pet_details, c.has_elderly_members,
          c.has_children, c.children_count, c.required_skills, c.budget_range, c.source, c.remarks,
          c.service_type, c.work_timings, c.food_preference, c.gender_preference, c.preferred_languages,
          c.religion_preference, c.expected_joining
        ]
      );
    }
    console.log('10 Clients seeded with complete profile data, images, requirements, and assigned reps.');

    console.log('Seeding 10 full-data Candidates...');
    for (const c of candidates) {
      await pool.execute(
        `INSERT INTO candidates 
        (id, full_name, phone, alternate_phone, age, address, city, state, religion, education, experience_years, languages, category, expected_salary, status, is_police_verified, is_medical_cleared, aadhaar_doc_url, pan_doc_url, passport_doc_url, police_verification_doc_url, medical_clearance_doc_url, sourced_by_id, profile_image_url, source) 
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE 
          full_name=VALUES(full_name), phone=VALUES(phone), alternate_phone=VALUES(alternate_phone),
          age=VALUES(age), address=VALUES(address), city=VALUES(city), state=VALUES(state),
          religion=VALUES(religion), education=VALUES(education), experience_years=VALUES(experience_years),
          languages=VALUES(languages), category=VALUES(category), expected_salary=VALUES(expected_salary),
          status=VALUES(status), is_police_verified=VALUES(is_police_verified),
          is_medical_cleared=VALUES(is_medical_cleared), aadhaar_doc_url=VALUES(aadhaar_doc_url),
          pan_doc_url=VALUES(pan_doc_url), passport_doc_url=VALUES(passport_doc_url),
          police_verification_doc_url=VALUES(police_verification_doc_url),
          medical_clearance_doc_url=VALUES(medical_clearance_doc_url),
          sourced_by_id=VALUES(sourced_by_id), profile_image_url=VALUES(profile_image_url),
          source=VALUES(source)`,
        [
          c.id, c.full_name, c.phone, c.alternate_phone, c.age, c.address, c.city, c.state,
          c.religion, c.education, c.experience_years, c.languages, c.category, c.expected_salary,
          c.status, c.is_police_verified, c.is_medical_cleared, c.aadhaar_doc_url, c.pan_doc_url,
          c.passport_doc_url, c.police_verification_doc_url, c.medical_clearance_doc_url,
          c.sourced_by_id, c.profile_image_url, c.source
        ]
      );
    }
    console.log('10 Candidates seeded with complete profile data, profile pictures, documents, and sourcing info.');

    console.log('Seeding completed successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Error during seeding:', err);
    process.exit(1);
  }
})();
