// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRQlYTa8qsq45P3oRsAc3id5ruDM2H4g4',
    appId: '1:190632344732:web:f5f2c0fc4f84c634b70159',
    messagingSenderId: '190632344732',
    projectId: 'verifiedmaids',
    authDomain: 'verifiedmaids.firebaseapp.com',
    storageBucket: 'verifiedmaids.firebasestorage.app',
    measurementId: 'G-1FZD5VX478',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlkfpwrkWSu9KGc4QWBS3Us9hHb5bo9jE',
    appId: '1:190632344732:android:502be03b0f45c390b70159',
    messagingSenderId: '190632344732',
    projectId: 'verifiedmaids',
    storageBucket: 'verifiedmaids.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMwziDLy_vAS0MbaizjjEyEQi_SsCgoE',
    appId: '1:190632344732:ios:926474c27f26a6f8b70159',
    messagingSenderId: '190632344732',
    projectId: 'verifiedmaids',
    storageBucket: 'verifiedmaids.firebasestorage.app',
    iosBundleId: 'com.legendarysoftware.crm.practiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOMwziDLy_vAS0MbaizjjEyEQi_SsCgoE',
    appId: '1:190632344732:ios:926474c27f26a6f8b70159',
    messagingSenderId: '190632344732',
    projectId: 'verifiedmaids',
    storageBucket: 'verifiedmaids.firebasestorage.app',
    iosBundleId: 'com.legendarysoftware.crm.practiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRQlYTa8qsq45P3oRsAc3id5ruDM2H4g4',
    appId: '1:190632344732:web:dec149000cf48ee0b70159',
    messagingSenderId: '190632344732',
    projectId: 'verifiedmaids',
    authDomain: 'verifiedmaids.firebaseapp.com',
    storageBucket: 'verifiedmaids.firebasestorage.app',
    measurementId: 'G-EVEF9MHB6K',
  );
}
